### ISSUE TITLE
Stream resources are not released

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [baidu/iotcore-sdk-java#1]
The resource of stream should be release in the end.
https://github.com/baidu/iotcore-sdk-java/blob/f586cfb729de37fd4b4bd0abf5e19768a6e67f34/iot-device-sdk-avatar-common/src/main/java/com/baidu/iot/device/sdk/avatar/common/utils/SSLSocketFactoryGenerator.java#L109-L114

**Comment by mafei6827** [comment]
Fixed in
https://github.com/baidu/iotcore-sdk-java/commit/ea26962912326d5da0aec1d77fa3669ab1ed449f#diff-e71d6a8d9ec7f66c32e34022bd4cd09194df5eebf05d85df3f1f1f6990cb054a
